update github

diff --git a/app/Dockerfile b/app/Dockerfile
--- a/app/Dockerfile
+++ b/app/Dockerfile
@@ -1,4 +1,25 @@
-FROM node:20-alpine
+# FROM node:20-alpine
+
+# WORKDIR /app
+
+# COPY package*.json ./
+
+# RUN npm install --only=production
+
+# COPY . .
+
+# RUN addgroup -S appgroup && adduser -S appuser -G appgroup
+
+# USER appuser
+
+# EXPOSE 3000
+
+# HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
+# CMD wget --quiet --tries=1 --spider http://localhost:3000/health || exit 1
+
+# CMD ["npm", "start"]
+
+FROM node:20-slim
 
 WORKDIR /app
 
@@ -8,13 +29,13 @@ RUN npm install --only=production
 
 COPY . .
 
-RUN addgroup -S appgroup && adduser -S appuser -G appgroup
+RUN groupadd -r appgroup && useradd -r -g appgroup appuser
 
 USER appuser
 
 EXPOSE 3000
 
 HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
-CMD wget --quiet --tries=1 --spider http://localhost:3000/health || exit 1
+CMD curl --fail http://localhost:3000/health || exit 1
 
 CMD ["npm", "start"]
